# Generated by Django 3.0.6 on 2020-05-13 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DfGoodsBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField()),
                ('type', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('image', models.CharField(max_length=128)),
                ('sort', models.IntegerField(blank=True, null=True)),
                ('ctime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'df_goods_banner',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DfGoodsSku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True)),
                ('unite', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.CharField(max_length=128)),
                ('stock', models.IntegerField(blank=True, default=1, null=True)),
                ('sales', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('ctime', models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 13, 17, 9, 54, 973896), null=True)),
                ('utime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'df_goods_sku',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DfGoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('logo', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=128)),
                ('ctime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'df_goods_type',
                'managed': False,
            },
        ),
    ]
