# Generated by Django 3.0.6 on 2020-05-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DfAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('receiver', models.CharField(blank=True, max_length=20, null=True)),
                ('addr', models.CharField(max_length=256)),
                ('zip_code', models.CharField(blank=True, max_length=6, null=True)),
                ('mobile', models.CharField(max_length=11)),
                ('is_default', models.IntegerField(blank=True, null=True)),
                ('ctime', models.DateTimeField(blank=True, null=True)),
                ('utime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'df_address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DfUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=128)),
                ('mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('ctime', models.DateTimeField(blank=True, null=True)),
                ('utime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'df_user',
                'managed': False,
            },
        ),
    ]
