# Generated by Django 3.0.6 on 2020-05-12 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200512_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ctime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 12, 22, 26, 14, 104607), null=True),
        ),
    ]
