# Generated by Django 3.0.6 on 2020-05-13 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200512_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ctime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 13, 17, 9, 54, 962922), null=True),
        ),
    ]
